### ISSUE TITLE
Technical Support email address and text should be a configuration setting

### ISSUE THREAD

**Issue by smkeesle** [karutaproject/karuta-backend#30]
The Technical Support text and email address should be configurable in a single properties file.

webapps/karuta/karuta/js/languages/locale_en.js:karutaStr['en']['technical_support']="Technical Support";
webapps/karuta/application/js/_init.js:var technical_support = "info.karuta@gmail.com";

**Comment by nobry** [comment]
Currently the properties file on the backend contains only server side related information.
Putting both client and backend configuration in the same file is touchy, since at some point I might have to ensure only specific information are sent through some interface.

I think at one point, it was discussed about having some configuration file (on the client side) to facilitate customization, colors, banner, logo, etc. The technical support email can be part of it.

**Comment by olivier-gerbe** [comment]
Technical Information email address are cnfigurable in frontend file _init.js
