### ISSUE TITLE
Build fails because of missing ojdbc6.jar dependency

### ISSUE THREAD

**Issue by eviweb** [karutaproject/karuta-backend#62]
Hi,

in the `pom.xml` file, is specified the following local dependency:
```xml
<dependency>
      <groupId>com.oracle</groupId>
      <artifactId>ojdbc</artifactId>
      <version>14</version>
      <scope>system</scope>
      <systemPath>${basedir}/WebContent/WEB-INF/lib/ojdbc6.jar</systemPath> <!-- must match file name -->
</dependency>
```
But the file is missing and this breaks the building process.
Best regards
Eric

**Comment by nobry** [comment]
Fixed in issue https://github.com/karutaproject/karuta-backend/commit/d1d1f967d43c4267f16d6adf4dddf08022b03181

I thought I had this commented. Anyway, Oracle forbid any kind of re-distribution of their binaries. If you need Oracle, you will have to download the jar file and place it in the specified systemPath (or change it if it suits you)
It's correctly disabled now.

Thanks.
